---
Example Study:
  classes:
    - high
    - medium
    - low
  covariates:
    covariate_1:
      intercepts:
        - 0.3
        - 0.4
        - 0.5
      coefficients:
        - -0.34
        - -0.45
        - 0.56
    covariate_2:
      intercepts:
        - 0.13
        - 0.41
        - 0.15
      coefficients:
        - 0.34
        - -0.55
        - -0.56
    covariate_3:
      intercepts:
        - -0.13
        - 0.41
        - 0.15
      coefficients:
        - 0.24
        - -0.7
        - 0.56
    covariate_4:
      intercepts:
        - 0.23
        - -0.41
        - 0.35
      coefficients:
        - 0.14
        - -0.25
        - -0.6
    covariate_5:
      intercepts:
        - -0.3
        - 0.241
        - -0.15
      coefficients:
        - 0.14
        - 0.55
        - -0.26
    covariate_6:
      intercepts:
        - -0.6
        - 0.41
        - -0.15
      coefficients:
        - -0.34
        - -0.15
        - 0.6
  outcome_probabilities:
    outcome_1:
      - 0.9
      - 0.05
      - 0.05
    outcome_2:
      - 0.1
      - 0.8
      - 0.1
    outcome_4:
      - 0.25
      - 0.5
      - 0.25
    outcome_5:
      - 0.33
      - 0.33
      - 0.33
