---
"Data-driven classification of health status of older adults with diabetes: The diabetes and aging study":
  covariate_label: "Comorbidities"
  class_intercepts:
    Healthy: 0
    Geriatric: 0.4
    Cardiac: 0.5
  covariate_coefficients:
    Arthritis:
      - 0
      - -0.45
      - 0.56
    Atrial Fibrillation:
      - 0
      - -0.55
      - -0.56
    Cancer:
      - 0
      - -0.7
      - 0.56
    Congestive Heart Failure:
      - 0
      - -0.25
      - -0.6
    Coronary Artery Disease:
      - 0
      - 0.55
      - -0.26
    Dementia:
      - 0
      - -0.15
      - 0.6
    Depression:
      - 0
      - -0.15
      - 0.6
    Emphysema/ Chronic Obstructive Pulmonary Disease (COPD):
      - 0
      - -0.15
      - 0.6
    End-Stage Renal Disease (ESRD):
      - 0
      - -0.15
      - 0.6
    Falls:
      - 0
      - -0.15
      - 0.6
    Foot ulcer:
      - 0
      - -0.15
      - 0.6
    Hypertension:
      - 0
      - -0.15
      - 0.6
    Liver Disease:
      - 0
      - -0.15
      - 0.6
    Lower Extremity Amputation:
      - 0
      - -0.15
      - 0.6
    Obesity:
      - 0
      - -0.15
      - 0.6
    Peripheral Vascular Disease:
      - 0
      - -0.15
      - 0.6
    Stroke:
      - 0
      - -0.15
      - 0.6
    Thyroid Disease:
      - 0
      - -0.15
      - 0.6
    Urinary Incontinence:
      - 0
      - -0.15
      - 0.6
  outcome_probabilities:
    Microvascular complications:
      - 0.9
      - 0.15
      - 0.35
    Cardiovascular complications:
      - 0.2
      - 0.8
      - 0.15
    Infection:
      - 0.25
      - 0.8
      - 0.25
    Hypoglycemia:
      - 0.93
      - 0.33
      - 0.33
    Hyperglycemia:
      - 0.1
      - 0.9
      - 0.1
    Mortality:
      - 0.9
      - 0.2
      - 0.8
    Combined non-mortality:
      - 0.8
      - 0.3
      - 0.1
    Combined outcome:
      - 0.9
      - 0.25
      - 0.05
