---
Example Study:
  covariate_label: "Covariate type"
  class_intercepts:
    high: 0.3
    medium: 0.4
    low: 0.5
  covariate_coefficients:
    covariate_1:
      - -0.34
      - -0.45
      - 0.56
    covariate_2:
      - 0.34
      - -0.55
      - -0.56
    covariate_3:
      - 0.24
      - -0.7
      - 0.56
    covariate_4:
      - 0.14
      - -0.25
      - -0.6
    covariate_5:
      - 0.14
      - 0.55
      - -0.26
    covariate_6:
      - -0.34
      - -0.15
      - 0.6
  outcome_probabilities:
    outcome_1:
      - 0.9
      - 0.05
      - 0.05
    outcome_2:
      - 0.1
      - 0.8
      - 0.1
    outcome_4:
      - 0.25
      - 0.5
      - 0.25
    outcome_5:
      - 0.33
      - 0.33
      - 0.33
