---
"Data-driven classification of health status of older adults with diabetes: The diabetes and aging study":
  covariate_label: "Comorbidities"
  prior_probabilities:
    Healthy: 0
    Geriatric: 0.4
    Cardiac: 0.5
  covariate_class_probabilities:
    Arthritis:
      - 0
      - 0.45
      - 0.56
    Atrial Fibrillation:
      - 0
      - 0.55
      - 0.56
    Cancer:
      - 0
      - 0.7
      - 0.56
    Congestive Heart Failure:
      - 0
      - 0.25
      - 0.6
    Coronary Artery Disease:
      - 0
      - 0.55
      - 0.26
    Dementia:
      - 0
      - 0.15
      - 0.6
    Depression:
      - 0
      - 0.15
      - 0.6
    Emphysema/ Chronic Obstructive Pulmonary Disease (COPD):
      - 0
      - 0.15
      - 0.6
    End-Stage Renal Disease (ESRD):
      - 0
      - 0.15
      - 0.6
    Falls:
      - 0
      - 0.15
      - 0.6
    Foot ulcer:
      - 0
      - 0.15
      - 0.6
    Hypertension:
      - 0
      - 0.15
      - 0.6
    Liver Disease:
      - 0
      - 0.15
      - 0.6
    Lower Extremity Amputation:
      - 0
      - 0.15
      - 0.6
    Obesity:
      - 0
      - 0.15
      - 0.6
    Peripheral Vascular Disease:
      - 0
      - 0.15
      - 0.6
    Stroke:
      - 0
      - 0.15
      - 0.6
    Thyroid Disease:
      - 0
      - 0.15
      - 0.6
    Urinary Incontinence:
      - 0
      - 0.15
      - 0.6
  outcome_probabilities:
    Hypertension:
      - 0.87
      - 0.95
      - 0.97
    Atrial fibrillation:
      - 0.05
      - 0.07
      - 0.50
    Congestive heart failure:
      - 0.02
      - 0.06
      - 0.59
    Coronary artery disease:
      - 0.07
      - 0.09
      - 0.59
    Stroke:
      - 0.01
      - 0.04
      - 0.15
    Peripheral vascular disease:
      - 0.06
      - 0.18
      - 0.51
    Foot ulcer:
      - 0.02
      - 0.08
      - 0.24
    Lower extremity amputation:
      - 0.0
      - 0.0
      - 0.04
    End-stage renal disease:
      - 0.01
      - 0.01
      - 0.08
    Liver disease:
      - 0.09
      - 0.23
      - 0.29
    Emphysema/ COPD:
      - 0.15
      - 0.34
      - 0.46
    Obesity:
      - 0.38
      - 0.57
      - 0.47
    Arthritis:
      - 0.31
      - 0.71
      - 0.52
    Depression:
      - 0.14
      - 0.56
      - 0.40
    Dementia:
      - 0.01
      - 0.08
      - 0.08
    Falls:
      - 0.09
      - 0.37
      - 0.38
    Urinary incontinence:
      - 0.04
      - 0.28
      - 0.15
    Thyroid disease:
      - 0.13
      - 0.31
      - 0.27
    Cancer:
      - 0.10
      - 0.14
      - 0.15
