name: Streamlit CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  streamlit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: streamlit/streamlit-app-action@v0.0.3
        with:
          app-path: app.py
